zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

honeycomb:
  beeline:
    service-name: petclinic_api_gateway
    dataset: petclinic_api_honeycomb_auto
    write-key: 601b1fc7e219279b3cde4e6b9eb49a1a
    sample-rate: 1
    enabled: true
    rest-template:
      enabled: true
    log-honeycomb-responses: true
    include-path-patterns: /**